### ISSUE TITLE
arm64?

### ISSUE THREAD

**Issue by fenopa** [Fullaxx/qbittorrent#1]
Hi, is it possible to use your ubuntu images in arm64? Would it be too much trouble to add support for it?

**Comment by fenopa** [comment]
ok i managed it by compiling the docker from source instead of pulling. (your base image needs to be compiled first and then this to make it work)

anyway everything is good but there is a problem, not sure if it's related to arm64 or general problem. when i set vnc password, and when trying to connect, it asks for password but when i enter password docker image crashes. when i don't set vnc password, it connects succesfully all fine but then when i close the vnc client, server crashes again. why is this happening do you know?

**Comment by fenopa** [comment]
update: not having this problem when using bionic image, weird

**Comment by Fullaxx** [comment]
that's very strange. I will say that I do not have the ability to test an arm64 image, but I was hoping it was as easy as forking the project and updating the FROM line in the docker file?
I would be happy to do that if that helps you, but I don't know anything about VNC crashing
